//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoInsuranceConnectionApp.Models
{
    using System;
    using System.Collections;


    public partial class Insuree : System.Collections.IEnumerable
    {
        public int InsureeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public int SpeedingTickets { get; set; }
        public bool DUI { get; set; }
        public bool CoverageType { get; set; }
        public int QuoteID { get; set; }
        public decimal QuoteMonthly { get; set; }
        public decimal QuoteYearly { get; set; }



        public Insuree(string firstName, string lastName, string emailAddress, DateTime dateOfBirth,
                       int carYear, string carMake, string carModel, int speedingTickets, bool dui,
                       bool coverageType)
        {
            FirstName = firstName;
            LastName = lastName;
            EmailAddress = emailAddress;
            DateOfBirth = dateOfBirth;
            CarYear = carYear;
            CarMake = carMake;
            CarModel = carModel;
            SpeedingTickets = speedingTickets;
            DUI = dui;
            CoverageType = coverageType;
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
